Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "jenkins-vm"

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "devops-jenkins"
    vb.memory = 4096
    vb.cpus   = 4
  end

  # Port Jenkins accessible depuis Windows sur http://localhost:8080
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  # Port de l'application web accessible depuis Windows sur http://localhost:9090
  config.vm.network "forwarded_port", guest: 9090, host: 9090

  config.vm.network "private_network", ip: "192.168.56.10"

  # Dossier partagé entre Windows et la VM (créé automatiquement)
  config.vm.synced_folder "./shared", "/vagrant_shared", create: true


end