Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "docker-vm"

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "devops-docker"
    vb.memory = 2048
    vb.cpus   = 2
  end

  # Conteneur de test Habit Tracker accessible depuis Windows sur http://localhost:9091
  config.vm.network "forwarded_port", guest: 9090, host: 9091

  # API Docker (TCP) — utilisée plus tard pour connecter Jenkins à cette VM
  config.vm.network "forwarded_port", guest: 2375, host: 2375

  config.vm.network "forwarded_port", guest: 8081, host: 8081

  config.vm.network "forwarded_port", guest: 80, host: 8082

  config.vm.network "private_network", ip: "192.168.56.11"

  config.vm.synced_folder "./shared", "/vagrant_shared", create: true

end